// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  hmr: true,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],  
  firebase: {
    apiKey: "AIzaSyDaLu8PFauHOr3MkdDzfN4kC03NxfznaOs",
    authDomain: "kuinbi-cb896.firebaseapp.com",
    databaseURL: "https://kuinbi-cb896.firebaseio.com",
    projectId: "kuinbi-cb896",
    storageBucket: "kuinbi-cb896.appspot.com",
    messagingSenderId: "180845560969",
    appId: "1:180845560969:web:a6b48a20e413c36ceff258",
    measurementId: "G-45QXCX58ZS"
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
